List<Map<String, String>> dialCodes = [
  {'name': 'Afghanistan', 'number': '93'},
  {'name': 'Albania', 'number': '355'},
  {'name': 'Algeria', 'number': '213'},
  {'name': 'American Samoa', 'number': '1 684'},
  {'name': 'Andorra', 'number': '376'},
  {'name': 'Angola', 'number': '244'},
  {'name': 'Anguilla', 'number': '1 264'},
  {'name': 'Antarctica', 'number': '672'},
  {'name': 'Antigua & Barbuda', 'number': '1 268'},
  {'name': 'Argentina', 'number': '54'},
  {'name': 'Armenia', 'number': '374'},
  {'name': 'Aruba', 'number': '297'},
  {'name': 'Australia', 'number': '61'},
  {'name': 'Austria', 'number': '43'},
  {'name': 'Azerbaijan', 'number': '994'},
  {'name': 'Bahamas', 'number': '1 242'},
  {'name': 'Bahrain', 'number': '973'},
  {'name': 'Bangladesh', 'number': '880'},
  {'name': 'Barbados', 'number': '1 246'},
  {'name': 'Belarus', 'number': '375'},
  {'name': 'Belgium', 'number': '32'},
  {'name': 'Belize', 'number': '501'},
  {'name': 'Benin', 'number': '229'},
  {'name': 'Bermuda', 'number': '1 441'},
  {'name': 'Bhutan', 'number': '975'},
  {'name': 'Bolivia', 'number': '591'},
  {'name': 'Caribbean Netherlands', 'number': '599'},
  {'name': 'Bosnia', 'number': '387'},
  {'name': 'Botswana', 'number': '267'},
  {'name': 'Bouvet Island', 'number': '47'},
  {'name': 'Brazil', 'number': '55'},
  {'name': 'British Indian Ocean Territory', 'number': '246'},
  {'name': 'British Virgin Islands', 'number': '1 284'},
  {'name': 'Brunei', 'number': '673'},
  {'name': 'Bulgaria', 'number': '359'},
  {'name': 'Burkina Faso', 'number': '226'},
  {'name': 'Burundi', 'number': '257'},
  {'name': 'Cape Verde', 'number': '238'},
  {'name': 'Cambodia', 'number': '855'},
  {'name': 'Cameroon', 'number': '237'},
  {'name': 'Canada', 'number': '1'},
  {'name': 'Cayman Islands', 'number': '1 345'},
  {'name': 'Central African Republic', 'number': '236'},
  {'name': 'Chad', 'number': '235'},
  {'name': 'Chile', 'number': '56'},
  {'name': 'China', 'number': '86'},
  {'name': 'Hong Kong', 'number': '852'},
  {'name': 'Macau', 'number': '853'},
  {'name': 'Christmas Island', 'number': '61'},
  {'name': 'Cocos (Keeling) Islands', 'number': '61'},
  {'name': 'Colombia', 'number': '57'},
  {'name': 'Comoros', 'number': '269'},
  {'name': 'Congo   Brazzaville', 'number': '242'},
  {'name': 'Cook Islands', 'number': '682'},
  {'name': 'Costa Rica', 'number': '506'},
  {'name': 'Croatia', 'number': '385'},
  {'name': 'Cuba', 'number': '53'},
  {'name': 'Curaçao', 'number': '599'},
  {'name': 'Cyprus', 'number': '357'},
  {'name': 'Czechia', 'number': '420'},
  {'name': 'Côte d’Ivoire', 'number': '225'},
  {'name': 'North Korea', 'number': '850'},
  {'name': 'Congo   Kinshasa', 'number': '243'},
  {'name': 'Denmark', 'number': '45'},
  {'name': 'Djibouti', 'number': '253'},
  {'name': 'Dominica', 'number': '1 767'},
  {'name': 'Dominican Republic', 'number': '1 809'},
  {'name': 'Dominican Republic', 'number': '1 829'},
  {'name': 'Dominican Republic', 'number': '1 849'},
  {'name': 'Ecuador', 'number': '593'},
  {'name': 'Egypt', 'number': '20'},
  {'name': 'El Salvador', 'number': '503'},
  {'name': 'Equatorial Guinea', 'number': '240'},
  {'name': 'Eritrea', 'number': '291'},
  {'name': 'Estonia', 'number': '372'},
  {'name': 'Eswatini', 'number': '268'},
  {'name': 'Ethiopia', 'number': '251'},
  {'name': 'Falkland Islands', 'number': '500'},
  {'name': 'Faroe Islands', 'number': '298'},
  {'name': 'Fiji', 'number': '679'},
  {'name': 'Finland', 'number': '358'},
  {'name': 'France', 'number': '33'},
  {'name': 'French Guiana', 'number': '594'},
  {'name': 'French Polynesia', 'number': '689'},
  {'name': 'French Southern Territories', 'number': '262'},
  {'name': 'Gabon', 'number': '241'},
  {'name': 'Gambia', 'number': '220'},
  {'name': 'Georgia', 'number': '995'},
  {'name': 'Germany', 'number': '49'},
  {'name': 'Ghana', 'number': '233'},
  {'name': 'Gibraltar', 'number': '350'},
  {'name': 'Greece', 'number': '30'},
  {'name': 'Greenland', 'number': '299'},
  {'name': 'Grenada', 'number': '1 473'},
  {'name': 'Guadeloupe', 'number': '590'},
  {'name': 'Guam', 'number': '1 671'},
  {'name': 'Guatemala', 'number': '502'},
  {'name': 'Guernsey', 'number': '44'},
  {'name': 'Guinea', 'number': '224'},
  {'name': 'Guinea-Bissau', 'number': '245'},
  {'name': 'Guyana', 'number': '592'},
  {'name': 'Haiti', 'number': '509'},
  {'name': 'Heard & McDonald Islands', 'number': '672'},
  {'name': 'Vatican City', 'number': '39 06'},
  {'name': 'Honduras', 'number': '504'},
  {'name': 'Hungary', 'number': '36'},
  {'name': 'Iceland', 'number': '354'},
  {'name': 'India', 'number': '91'},
  {'name': 'Indonesia', 'number': '62'},
  {'name': 'Iran', 'number': '98'},
  {'name': 'Iraq', 'number': '964'},
  {'name': 'Ireland', 'number': '353'},
  {'name': 'Isle of Man', 'number': '44'},
  {'name': 'Israel', 'number': '972'},
  {'name': 'Italy', 'number': '39'},
  {'name': 'Jamaica', 'number': '1 876'},
  {'name': 'Japan', 'number': '81'},
  {'name': 'Jersey', 'number': '44'},
  {'name': 'Jordan', 'number': '962'},
  {'name': 'Kazakhstan', 'number': '7'},
  {'name': 'Kenya', 'number': '254'},
  {'name': 'Kiribati', 'number': '686'},
  {'name': 'Kuwait', 'number': '965'},
  {'name': 'Kyrgyzstan', 'number': '996'},
  {'name': 'Laos', 'number': '856'},
  {'name': 'Latvia', 'number': '371'},
  {'name': 'Lebanon', 'number': '961'},
  {'name': 'Lesotho', 'number': '266'},
  {'name': 'Liberia', 'number': '231'},
  {'name': 'Libya', 'number': '218'},
  {'name': 'Liechtenstein', 'number': '423'},
  {'name': 'Lithuania', 'number': '370'},
  {'name': 'Luxembourg', 'number': '352'},
  {'name': 'Madagascar', 'number': '261'},
  {'name': 'Malawi', 'number': '265'},
  {'name': 'Malaysia', 'number': '60'},
  {'name': 'Maldives', 'number': '960'},
  {'name': 'Mali', 'number': '223'},
  {'name': 'Malta', 'number': '356'},
  {'name': 'Marshall Islands', 'number': '692'},
  {'name': 'Martinique', 'number': '596'},
  {'name': 'Mauritania', 'number': '222'},
  {'name': 'Mauritius', 'number': '230'},
  {'name': 'Mayotte', 'number': '262'},
  {'name': 'Mexico', 'number': '52'},
  {'name': 'Micronesia', 'number': '691'},
  {'name': 'Monaco', 'number': '377'},
  {'name': 'Mongolia', 'number': '976'},
  {'name': 'Montenegro', 'number': '382'},
  {'name': 'Montserrat', 'number': '1 664'},
  {'name': 'Morocco', 'number': '212'},
  {'name': 'Mozambique', 'number': '258'},
  {'name': 'Myanmar', 'number': '95'},
  {'name': 'Namibia', 'number': '264'},
  {'name': 'Nauru', 'number': '674'},
  {'name': 'Nepal', 'number': '977'},
  {'name': 'Netherlands', 'number': '31'},
  {'name': 'New Caledonia', 'number': '687'},
  {'name': 'New Zealand', 'number': '64'},
  {'name': 'Nicaragua', 'number': '505'},
  {'name': 'Niger', 'number': '227'},
  {'name': 'Nigeria', 'number': '234'},
  {'name': 'Niue', 'number': '683'},
  {'name': 'Norfolk Island', 'number': '672'},
  {'name': 'Northern Mariana Islands', 'number': '1 670'},
  {'name': 'Norway', 'number': '47'},
  {'name': 'Oman', 'number': '968'},
  {'name': 'Pakistan', 'number': '92'},
  {'name': 'Palau', 'number': '680'},
  {'name': 'Panama', 'number': '507'},
  {'name': 'Papua New Guinea', 'number': '675'},
  {'name': 'Paraguay', 'number': '595'},
  {'name': 'Peru', 'number': '51'},
  {'name': 'Philippines', 'number': '63'},
  {'name': 'Pitcairn Islands', 'number': '870'},
  {'name': 'Poland', 'number': '48'},
  {'name': 'Portugal', 'number': '351'},
  {'name': 'Puerto Rico', 'number': '1'},
  {'name': 'Qatar', 'number': '974'},
  {'name': 'South Korea', 'number': '82'},
  {'name': 'Moldova', 'number': '373'},
  {'name': 'Romania', 'number': '40'},
  {'name': 'Russia', 'number': '7'},
  {'name': 'Rwanda', 'number': '250'},
  {'name': 'Réunion', 'number': '262'},
  {'name': 'St. Barthélemy', 'number': '590'},
  {'name': 'St. Helena', 'number': '290'},
  {'name': 'St. Kitts & Nevis', 'number': '1 869'},
  {'name': 'St. Lucia', 'number': '1 758'},
  {'name': 'St. Martin', 'number': '590'},
  {'name': 'St. Pierre & Miquelon', 'number': '508'},
  {'name': 'St. Vincent & Grenadines', 'number': '1 784'},
  {'name': 'Samoa', 'number': '685'},
  {'name': 'San Marino', 'number': '378'},
  {'name': 'São Tomé & Príncipe', 'number': '239'},
  {'name': 'Saudi Arabia', 'number': '966'},
  {'name': 'Senegal', 'number': '221'},
  {'name': 'Serbia', 'number': '381'},
  {'name': 'Seychelles', 'number': '248'},
  {'name': 'Sierra Leone', 'number': '232'},
  {'name': 'Singapore', 'number': '65'},
  {'name': 'Sint Maarten', 'number': '1 721'},
  {'name': 'Slovakia', 'number': '421'},
  {'name': 'Slovenia', 'number': '386'},
  {'name': 'Solomon Islands', 'number': '677'},
  {'name': 'Somalia', 'number': '252'},
  {'name': 'South Africa', 'number': '27'},
  {'name': 'South Georgia & South Sandwich Islands', 'number': '500'},
  {'name': 'South Sudan', 'number': '211'},
  {'name': 'Spain', 'number': '34'},
  {'name': 'Sri Lanka', 'number': '94'},
  {'name': 'Palestine', 'number': '970'},
  {'name': 'Sudan', 'number': '249'},
  {'name': 'Suriname', 'number': '597'},
  {'name': 'Svalbard & Jan Mayen', 'number': '47'},
  {'name': 'Sweden', 'number': '46'},
  {'name': 'Switzerland', 'number': '41'},
  {'name': 'Syria', 'number': '963'},
  {'name': 'Tajikistan', 'number': '992'},
  {'name': 'Thailand', 'number': '66'},
  {'name': 'North Macedonia', 'number': '389'},
  {'name': 'Timor-Leste', 'number': '670'},
  {'name': 'Togo', 'number': '228'},
  {'name': 'Tokelau', 'number': '690'},
  {'name': 'Tonga', 'number': '676'},
  {'name': 'Trinidad & Tobago', 'number': '1 868'},
  {'name': 'Tunisia', 'number': '216'},
  {'name': 'Turkey', 'number': '90'},
  {'name': 'Turkmenistan', 'number': '993'},
  {'name': 'Turks & Caicos Islands', 'number': '1 649'},
  {'name': 'Tuvalu', 'number': '688'},
  {'name': 'Uganda', 'number': '256'},
  {'name': 'Ukraine', 'number': '380'},
  {'name': 'United Arab Emirates', 'number': '971'},
  {'name': 'UK', 'number': '44'},
  {'name': 'Tanzania', 'number': '255'},
  {'name': 'U.S. Virgin Islands', 'number': '1 340'},
  {'name': 'US', 'number': '1'},
  {'name': 'Uruguay', 'number': '598'},
  {'name': 'Uzbekistan', 'number': '998'},
  {'name': 'Vanuatu', 'number': '678'},
  {'name': 'Venezuela', 'number': '58'},
  {'name': 'Vietnam', 'number': '84'},
  {'name': 'Wallis & Futuna', 'number': '681'},
  {'name': 'Western Sahara', 'number': '212'},
  {'name': 'Yemen', 'number': '967'},
  {'name': 'Zambia', 'number': '260'},
  {'name': 'Zimbabwe', 'number': '263'},
];
